# bmlib — shared library for biomedical literature tools
# Copyright (C) 2024-2026 Dr Horst Herb
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Per-agent performance accounting.

:class:`PerformanceMetrics` is instance-scoped and answers "what did this
agent do".  It is deliberately independent of
:class:`bmlib.llm.TokenTracker`, the process-wide cost ledger that answers
"what has this process spent" — an agent never writes to global state.
"""

from __future__ import annotations

import threading
import time
from dataclasses import dataclass, field
from typing import Any


@dataclass
class PerformanceMetrics:
    """Cumulative statistics for one agent's LLM calls.

    Thread-safe: an agent instance may be shared across workers, and ``+=``
    is a read-modify-write.

    The ``threading.Lock`` field means an instance cannot be
    ``copy.deepcopy()``-ed or ``pickle``-d directly — both raise
    ``TypeError`` on the lock. Use :meth:`snapshot` to get an independent,
    lock-free copy instead.

    Attributes:
        total_prompt_tokens: Tokens sent to the model.
        total_completion_tokens: Tokens generated by the model.
        total_tokens: Sum of the two.
        total_requests: Successful requests, counting every attempt.
        total_retries: Attempts beyond the first, across all requests.
        total_wall_time_seconds: Wall-clock time inside successful requests.
        start_time: When collection started, or ``None``.
        end_time: When collection ended, or ``None`` if still running.
    """

    total_prompt_tokens: int = 0
    total_completion_tokens: int = 0
    total_tokens: int = 0
    total_requests: int = 0
    total_retries: int = 0
    total_wall_time_seconds: float = 0.0
    start_time: float | None = None
    end_time: float | None = None
    _lock: threading.Lock = field(
        default_factory=threading.Lock, init=False, repr=False, compare=False
    )

    def add_request(
        self, prompt_tokens: int, completion_tokens: int, wall_time_seconds: float
    ) -> None:
        """Record one successful LLM request."""
        with self._lock:
            self.total_prompt_tokens += prompt_tokens
            self.total_completion_tokens += completion_tokens
            self.total_tokens += prompt_tokens + completion_tokens
            self.total_requests += 1
            self.total_wall_time_seconds += wall_time_seconds

    def add_retry(self) -> None:
        """Record one retry attempt."""
        with self._lock:
            self.total_retries += 1

    def mark_start(self) -> None:
        """Mark the start of a collection period, clearing any end mark."""
        with self._lock:
            self.start_time = time.time()
            self.end_time = None

    def mark_end(self) -> None:
        """Mark the end of a collection period."""
        with self._lock:
            self.end_time = time.time()

    def reset(self) -> None:
        """Clear all counters and marks."""
        with self._lock:
            self.total_prompt_tokens = 0
            self.total_completion_tokens = 0
            self.total_tokens = 0
            self.total_requests = 0
            self.total_retries = 0
            self.total_wall_time_seconds = 0.0
            self.start_time = None
            self.end_time = None

    def snapshot(self) -> PerformanceMetrics:
        """Return an independent copy, read under the lock."""
        with self._lock:
            copy = PerformanceMetrics(
                total_prompt_tokens=self.total_prompt_tokens,
                total_completion_tokens=self.total_completion_tokens,
                total_tokens=self.total_tokens,
                total_requests=self.total_requests,
                total_retries=self.total_retries,
                total_wall_time_seconds=self.total_wall_time_seconds,
                start_time=self.start_time,
                end_time=self.end_time,
            )
        return copy

    @property
    def elapsed_time_seconds(self) -> float:
        """Seconds from :meth:`mark_start` to :meth:`mark_end`, or to now."""
        if self.start_time is None:
            return 0.0
        end = self.end_time if self.end_time is not None else time.time()
        return end - self.start_time

    @property
    def tokens_per_second(self) -> float:
        """Completion tokens per second of wall time.

        Wall time, not model-inference time: no provider reports inference
        time through bmlib, and this is the throughput the caller observed.
        """
        if self.total_wall_time_seconds > 0:
            return self.total_completion_tokens / self.total_wall_time_seconds
        return 0.0

    @property
    def average_tokens_per_request(self) -> float:
        """Mean total tokens per request."""
        if self.total_requests > 0:
            return self.total_tokens / self.total_requests
        return 0.0

    def to_dict(self) -> dict[str, Any]:
        """Serialise to a plain dict, derived values included."""
        return {
            "total_prompt_tokens": self.total_prompt_tokens,
            "total_completion_tokens": self.total_completion_tokens,
            "total_tokens": self.total_tokens,
            "total_requests": self.total_requests,
            "total_retries": self.total_retries,
            "total_wall_time_seconds": round(self.total_wall_time_seconds, 3),
            "elapsed_time_seconds": round(self.elapsed_time_seconds, 3),
            "tokens_per_second": round(self.tokens_per_second, 2),
            "average_tokens_per_request": round(self.average_tokens_per_request, 1),
            "start_time": self.start_time,
            "end_time": self.end_time,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> PerformanceMetrics:
        """Rebuild from :meth:`to_dict` output, ignoring derived values.

        :meth:`to_dict` rounds ``total_wall_time_seconds`` to 3 decimal
        places, so a round trip through ``to_dict``/``from_dict`` is not
        bit-exact for sub-millisecond timings — only accurate to the
        millisecond.
        """
        return cls(
            total_prompt_tokens=data.get("total_prompt_tokens", 0),
            total_completion_tokens=data.get("total_completion_tokens", 0),
            total_tokens=data.get("total_tokens", 0),
            total_requests=data.get("total_requests", 0),
            total_retries=data.get("total_retries", 0),
            total_wall_time_seconds=data.get("total_wall_time_seconds", 0.0),
            start_time=data.get("start_time"),
            end_time=data.get("end_time"),
        )

    def format_report(self, title: str | None = None) -> str:
        """Render a human-readable report.

        Args:
            title: Heading to print above the numbers.  Omitted entirely
                when ``None``.
        """
        lines: list[str] = []
        if title:
            lines.append(f"=== {title} Performance Metrics ===")

        retries = f" ({self.total_retries} retries)" if self.total_retries else ""
        lines.append(f"Requests:     {self.total_requests:,}{retries}")
        lines.append(
            f"Tokens:       {self.total_tokens:,} total "
            f"({self.total_prompt_tokens:,} prompt + "
            f"{self.total_completion_tokens:,} completion)"
        )

        elapsed = self.elapsed_time_seconds
        if elapsed > 0:
            lines.append(
                f"Time:         {elapsed:.2f}s elapsed "
                f"({self.total_wall_time_seconds:.2f}s in requests)"
            )
        else:
            lines.append(f"Time:         {self.total_wall_time_seconds:.2f}s in requests")

        if self.tokens_per_second > 0:
            lines.append(f"Speed:        {self.tokens_per_second:.1f} tokens/sec")
        if self.total_requests > 0:
            lines.append(f"Avg/Request:  {self.average_tokens_per_request:.0f} tokens")

        return "\n".join(lines)
