#!/usr/bin/env python3
"""Dump bmlib's text utilities and processor behaviour as JSON, for the Rust port.

The second differential oracle (the first is `dump_citations.py`). See
`docs/plans/2026-09-26-rust-port-roadblocks.md` §7 for why these exist: a
translated test encodes the *porter's* reading of an expectation, while a case
generated by running the Python library cannot be wrong in the same direction
as the port.

Reads a JSON list of cases on stdin, writes a JSON list of results on stdout.

    .venv/bin/python rust/oracle/dump_context.py < rust/oracle/context_cases.json
"""

from __future__ import annotations

import json
import sys

from bmlib.context_processor import (
    ConsolidationStrategy,
    ExtractionResult,
    IterativeContextProcessor,
    OversizedItemStrategy,
    ProcessingConfig,
    ProcessingStatus,
)
from bmlib.llm.text_utils import (
    combine_title_and_text,
    get_text_with_priority,
    TextChunker,
    chunk_text,
)


# ---------------------------------------------------------------------------
# Deterministic stand-ins for a caller's processor
# ---------------------------------------------------------------------------


class EchoProcessor(IterativeContextProcessor):
    """Extraction returns a fixed string, so the harness is reproducible."""

    def __init__(self, reply: str = "ok", **kwargs):
        super().__init__(**kwargs)
        self.reply = reply

    def format_item(self, item, index):
        return str(item)

    def extract_from_batch(self, batch_content, query, batch_metadata):
        return ExtractionResult(content=self.reply)


class DecoratingProcessor(EchoProcessor):
    """`format_item` adds width, so raw and formatted sizes differ."""

    def format_item(self, item, index):
        return f"[{index}] {item}"

    def split_oversized_item(self, item, max_chars, overlap=0):
        return super().split_oversized_item(item, max_chars, overlap)


class FailingProcessor(EchoProcessor):
    """Extraction raises for the chosen batch indices."""

    def __init__(self, fail_on=None, **kwargs):
        super().__init__(**kwargs)
        self.fail_on = set(fail_on or [])

    def extract_from_batch(self, batch_content, query, batch_metadata):
        if batch_metadata["batch_index"] in self.fail_on:
            raise RuntimeError("boom")
        return ExtractionResult(content=self.reply)


class GrowingProcessor(EchoProcessor):
    """`extract_from_batch` returns the batch, so recursion is forced."""

    def extract_from_batch(self, batch_content, query, batch_metadata):
        return ExtractionResult(content=batch_content)


def _config(spec: dict) -> ProcessingConfig:
    kwargs = dict(spec or {})
    for key, enum in (("oversized_item_strategy", OversizedItemStrategy),
                      ("consolidation_strategy", ConsolidationStrategy)):
        if key in kwargs:
            kwargs[key] = enum(kwargs[key])
    return ProcessingConfig(**kwargs)


def _result(r) -> dict:
    return {
        "content": r.content,
        "confidence": r.confidence,
        "is_error": r.is_error,
        "error_message": r.error_message,
        "recursion_level": r.recursion_level,
        "source_indices": r.source_indices,
        "content_length": r.content_length,
        "is_valid": r.is_valid,
    }


def _processing_result(pr) -> dict:
    return {
        "content": pr.content,
        "status": pr.status.value,
        "total_items_processed": pr.total_items_processed,
        "batches_created": pr.batches_created,
        "recursion_levels_used": pr.recursion_levels_used,
        "failed_batches": pr.failed_batches,
        "skipped_items": pr.skipped_items,
        "successful_batches": pr.successful_batches,
        "success_rate": pr.success_rate,
        "is_complete": pr.is_complete,
        "is_partial": pr.is_partial,
        "has_failures": pr.has_failures,
        "error_message": pr.error_message,
        "final_result": _result(pr.final_result),
        "batches_per_level": pr.processing_stats.get("batches_per_level"),
        "items_per_level": pr.processing_stats.get("items_per_level"),
    }


def run(case: dict):
    fn = case["fn"]
    args = case.get("args", {})

    # --- TextChunker ------------------------------------------------------
    if fn == "chunk_text":
        chunks = chunk_text(
            args["text"],
            chunk_size=args["chunk_size"],
            overlap=args.get("overlap", 0),
            boundary_aware=args.get("boundary_aware", True),
            min_chunk_size=args.get("min_chunk_size", 500),
        )
        return [
            {
                "content": c.content,
                "start_pos": c.start_pos,
                "end_pos": c.end_pos,
                "chunk_index": c.chunk_index,
                "total_chunks": c.total_chunks,
                "size": c.size,
            }
            for c in chunks
        ]

    if fn == "chunk_info":
        return TextChunker(
            chunk_size=args["chunk_size"],
            overlap=args.get("overlap", 0),
            boundary_aware=args.get("boundary_aware", True),
            min_chunk_size=args.get("min_chunk_size", 500),
        ).get_chunk_info(args["text"])

    if fn == "chunker_error":
        try:
            TextChunker(chunk_size=args["chunk_size"], overlap=args.get("overlap", 0))
            return {"raised": False}
        except ValueError as exc:
            return {"raised": True, "type": "ValueError", "message": str(exc)}

    # --- text helpers -----------------------------------------------------
    if fn == "get_text_with_priority":
        text, source = get_text_with_priority(
            args["document"], args.get("prefer_full_text", True)
        )
        return {"text": text, "source": source}

    if fn == "combine_title_and_text":
        return combine_title_and_text(
            args["title"], args["text"], args.get("max_title_length", 500)
        )

    # --- config -----------------------------------------------------------
    if fn == "config_validate":
        try:
            _config(args["config"])
            return {"raised": False}
        except ValueError as exc:
            return {"raised": True, "message": str(exc), "type": type(exc).__name__}

    # --- processor --------------------------------------------------------
    if fn == "process":
        kind = args.get("processor", "echo")
        kwargs = {"config": _config(args.get("config", {}))}
        if kind == "echo":
            proc = EchoProcessor(reply=args.get("reply", "ok"), **kwargs)
        elif kind == "decorating":
            proc = DecoratingProcessor(reply=args.get("reply", "ok"), **kwargs)
        elif kind == "failing":
            proc = FailingProcessor(fail_on=args.get("fail_on", []), reply=args.get("reply", "ok"), **kwargs)
        elif kind == "growing":
            proc = GrowingProcessor(**kwargs)
        else:
            raise ValueError(f"unknown processor {kind!r}")
        pr = proc.process(
            list(args["items"]),
            query=args.get("query", "q"),
            store_intermediate=args.get("store_intermediate", False),
        )
        out = _processing_result(pr)
        if args.get("store_intermediate"):
            out["intermediate_result_counts"] = [len(level) for level in (pr.intermediate_results or [])]
        return out

    raise ValueError(f"unknown fn {fn!r}")


def main() -> int:
    cases = json.load(sys.stdin)
    results = []
    for case in cases:
        try:
            results.append({"name": case["name"], "ok": True, "value": run(case)})
        except Exception as exc:  # noqa: BLE001 - the oracle records failures too
            results.append({"name": case["name"], "ok": False, "error": f"{type(exc).__name__}: {exc}"})
    json.dump(results, sys.stdout, indent=2, sort_keys=True, ensure_ascii=False)
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
