// bmlib — shared library for biomedical literature tools
// Copyright (C) 2024-2026 Dr Horst Herb
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

//! The differential oracle: Rust versus Python, over one shared corpus.
//!
//! The port plan (§7) calls for an oracle that compares **semantic** fields
//! against the Python implementation rather than JSON text. This is that
//! oracle for `citations/`.
//!
//! # How it works
//!
//! `tests/data/citations_cases.json` is a list of `{name, fn, args}` records.
//! `rust/oracle/dump_citations.py` runs each one through the Python library and
//! writes `tests/data/citations_expected.json`. This test runs the same case
//! through the Rust port and asserts the two JSON values are *equal* — comparing
//! parsed values, so key order and whitespace cannot matter.
//!
//! Regenerating the expectations, from the repository root:
//!
//! ```text
//! .venv/bin/python rust/oracle/dump_citations.py < rust/oracle/cases.json \
//!     > rust/bmlib/tests/data/citations_expected.json
//! ```
//!
//! Both files are committed so the test runs with no Python present, which is
//! what makes it usable in CI for a Rust-only consumer.
//!
//! # Why this exists, given the ported tests
//!
//! The ported Python tests are necessary and not sufficient: they are a
//! translation, so they encode the *porter's* reading of each expectation. This
//! corpus is generated by running the Python library itself, so a case here
//! cannot be wrong in the same direction as the port. It is the only instrument
//! that can tell "the port agrees with Python" from "the port agrees with
//! itself".

use std::collections::HashMap;

use bmlib::citations::models::{Citation, CitationStyle, DocumentMetadata};
use bmlib::citations::{
    author_surname, build_references, citation_positions, citations_in_range, count_citations,
    count_unique_citations, create_citation_marker, extract_document_id_from_citation,
    extract_label_from_citation, find_adjacent_citations, find_missing_documents,
    format_citation_group, format_document, parse_citations, replace_all_citations_with_numbers,
    replace_citation_with_number, unique_document_ids, validate_marker, CitationFormatter,
};
use serde_json::{json, Value};

const CASES: &str = include_str!("data/citations_cases.json");
const EXPECTED: &str = include_str!("data/citations_expected.json");

/// One cited document from a case's `metadata` object.
fn metadata_from(spec: &Value) -> DocumentMetadata {
    DocumentMetadata::from_json(spec).expect("metadata spec should deserialise")
}

/// A case's `metadata` as an id-keyed map.
fn metadata_map(spec: &Value) -> HashMap<i64, DocumentMetadata> {
    spec.as_object()
        .expect("metadata map")
        .iter()
        .map(|(k, v)| (k.parse::<i64>().expect("numeric key"), metadata_from(v)))
        .collect()
}

fn citation_from(spec: &Value) -> Citation {
    Citation {
        document_id: spec["document_id"].as_i64().unwrap_or(0),
        label: spec["label"].as_str().unwrap_or_default().to_string(),
        position: spec["position"].as_u64().unwrap_or(0) as usize,
        text: spec["text"].as_str().unwrap_or_default().to_string(),
    }
}

fn id_to_number(spec: &Value) -> HashMap<i64, usize> {
    spec.as_object()
        .expect("id_to_number map")
        .iter()
        .map(|(k, v)| {
            (
                k.parse::<i64>().expect("numeric key"),
                v.as_u64().expect("numeric value") as usize,
            )
        })
        .collect()
}

fn style_of(args: &Value) -> CitationStyle {
    match args.get("style").and_then(Value::as_str) {
        Some("apa") => CitationStyle::Apa,
        Some("harvard") => CitationStyle::Harvard,
        Some("chicago") => CitationStyle::Chicago,
        _ => CitationStyle::Vancouver,
    }
}

/// Run one case and return its result as JSON.
fn run(case: &Value) -> Value {
    let name = case["name"].as_str().unwrap_or_default();
    let fn_name = case["fn"].as_str().unwrap_or_default();
    let args = &case["args"];
    let text = args["text"].as_str().unwrap_or_default();

    match fn_name {
        "author_surname" => json!(author_surname(args["author"].as_str().unwrap_or_default())),
        "parse_citations" => json!(parse_citations(text)
            .iter()
            .map(|c| json!({"document_id": c.document_id, "label": c.label, "position": c.position, "text": c.text}))
            .collect::<Vec<_>>()),
        "unique_document_ids" => json!(unique_document_ids(text)),
        "count_citations" => json!(count_citations(text)),
        "count_unique_citations" => json!(count_unique_citations(text)),
        "citation_positions" => {
            let map: serde_json::Map<String, Value> = citation_positions(text)
                .into_iter()
                .map(|(id, positions)| (id.to_string(), json!(positions)))
                .collect();
            Value::Object(map)
        }
        "citations_in_range" => json!(citations_in_range(
            text,
            args["start"].as_u64().unwrap_or(0) as usize,
            args["end"].as_u64().unwrap_or(0) as usize
        )
        .iter()
        .map(|c| json!({"document_id": c.document_id, "label": c.label, "position": c.position, "text": c.text}))
        .collect::<Vec<_>>()),
        "create_citation_marker" => json!(create_citation_marker(
            args["document_id"].as_i64().unwrap_or(0),
            args["label"].as_str().unwrap_or_default()
        )),
        "replace_citation_with_number" => json!(replace_citation_with_number(
            text,
            args["document_id"].as_i64().unwrap_or(0),
            args["number"].as_u64().unwrap_or(0) as usize
        )),
        "replace_all_citations_with_numbers" => {
            json!(replace_all_citations_with_numbers(text, &id_to_number(&args["id_to_number"])))
        }
        "find_adjacent_citations" => json!(find_adjacent_citations(text)
            .iter()
            .map(|group| group
                .iter()
                .map(|c| json!({"document_id": c.document_id, "label": c.label, "position": c.position, "text": c.text}))
                .collect::<Vec<_>>())
            .collect::<Vec<_>>()),
        "format_citation_group" => {
            let group: Vec<Citation> = args["citations"]
                .as_array()
                .expect("citations array")
                .iter()
                .map(citation_from)
                .collect();
            json!(format_citation_group(
                &group,
                &id_to_number(&args["id_to_number"]),
                args.get("combine_sequential")
                    .and_then(Value::as_bool)
                    .unwrap_or(true)
            ))
        }
        "validate_citation_marker" => match validate_marker(args["marker"].as_str().unwrap_or_default())
        {
            Ok(()) => json!({"ok": true, "reason": Value::Null}),
            Err(reason) => json!({"ok": false, "reason": reason}),
        },
        "extract_label_from_citation" => {
            json!(extract_label_from_citation(args["marker"].as_str().unwrap_or_default()))
        }
        "extract_document_id_from_citation" => {
            json!(extract_document_id_from_citation(args["marker"].as_str().unwrap_or_default()))
        }
        "format_reference" => {
            let m = metadata_from(&args["metadata"]);
            let f = CitationFormatter::new(style_of(args));
            json!(f.format_reference(&m, args.get("number").and_then(Value::as_u64).map(|n| n as usize)))
        }
        "format_inline_citation" => {
            let m = metadata_from(&args["metadata"]);
            let f = CitationFormatter::new(style_of(args));
            json!(f.format_inline_citation(&m, args.get("number").and_then(Value::as_u64).map(|n| n as usize)))
        }
        "generate_label" => json!(metadata_from(&args["metadata"]).generate_label()),
        "first_author_surname" => json!(metadata_from(&args["metadata"]).first_author_surname()),
        "build_references" => {
            let (text, refs) = build_references(
                text,
                &metadata_map(&args["metadata"]),
                style_of(args),
                args.get("combine_sequential")
                    .and_then(Value::as_bool)
                    .unwrap_or(true),
            );
            json!({
                "text": text,
                "references": refs.iter().map(|r| r.to_json().unwrap()).collect::<Vec<_>>(),
            })
        }
        "format_document" => json!(format_document(
            text,
            &metadata_map(&args["metadata"]),
            style_of(args),
            args.get("include_reference_list")
                .and_then(Value::as_bool)
                .unwrap_or(true),
            args.get("combine_sequential")
                .and_then(Value::as_bool)
                .unwrap_or(true),
        )),
        "find_missing_documents" => json!(find_missing_documents(text, &metadata_map(&args["metadata"]))
            .iter()
            .map(|c| json!({"document_id": c.document_id, "label": c.label, "position": c.position, "text": c.text}))
            .collect::<Vec<_>>()),
        other => panic!("case {name:?}: unknown fn {other:?}"),
    }
}

#[test]
fn the_port_agrees_with_python_on_every_case() {
    let cases: Value = serde_json::from_str(CASES).expect("cases parse");
    let expected: Value = serde_json::from_str(EXPECTED).expect("expected parse");
    let cases = cases.as_array().expect("cases is a list");
    let expected = expected.as_array().expect("expected is a list");
    assert_eq!(
        cases.len(),
        expected.len(),
        "the case file and the expected file disagree on how many cases there are — \
         regenerate the expectations"
    );

    let mut failures: Vec<String> = Vec::new();
    for (case, want) in cases.iter().zip(expected.iter()) {
        let name = case["name"].as_str().unwrap_or_default();
        assert_eq!(
            name,
            want["name"].as_str().unwrap_or_default(),
            "case/expected name mismatch — the two files are out of step"
        );
        if !want["ok"].as_bool().unwrap_or(false) {
            panic!(
                "case {name:?} errored in Python: {} — a case that does not run there \
                 cannot be a differential expectation",
                want["error"]
            );
        }
        let got = run(case);
        if got != want["value"] {
            failures.push(format!(
                "  {name}\n    python: {}\n    rust:   {}",
                serde_json::to_string(&want["value"]).unwrap_or_default(),
                serde_json::to_string(&got).unwrap_or_default()
            ));
        }
    }

    assert!(
        failures.is_empty(),
        "{} of {} cases diverge from Python:\n{}",
        failures.len(),
        cases.len(),
        failures.join("\n")
    );
}
