// bmlib — shared library for biomedical literature tools
// Copyright (C) 2024-2026 Dr Horst Herb
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

//! Citations — the named tests.
//!
//! [`citations_oracle`] is the broad instrument: 93 cases generated by running
//! the Python library, diffed semantically. This file is the *reasoned* half —
//! tests that say what a behaviour is for, and the regression tests for the
//! defect the port fixes.
//!
//! Anything already covered by the oracle is deliberately **not** repeated
//! here. What is here is: the defect fix, the upstream-faithful oddities that
//! look like bugs, and the properties a reader needs stated.

use bmlib::citations::models::{author_surname, CitationStyle, DocumentMetadata};
use bmlib::citations::{CitationFormatter, MAX_AUTHORS_BEFORE_ET_AL};

fn metadata(authors: &[&str], year: Option<i64>) -> DocumentMetadata {
    let mut m = DocumentMetadata::new(1, "T");
    m.authors = authors.iter().map(|a| (*a).to_string()).collect();
    m.year = year;
    m
}

// ---------------------------------------------------------------------------
// The defect this port fixes rather than reproduces — issue #296
// ---------------------------------------------------------------------------

/// Python's inline formatters branch on `len(metadata.authors)` — the raw
/// list — while the reference formatters filter whitespace-only entries
/// first. So a blank author made the two disagree:
///
/// ```text
/// authors = ["John Smith", "Anna Johnson", "   "]
///   reference: "Smith, J. & Johnson, A. (2023) T."      <- 2 named
///   inline:    "(Smith et al., 2023)"                   <- counted 3
/// ```
///
/// The port counts named authors everywhere, so the two cannot disagree.
#[test]
fn a_trailing_blank_author_does_not_make_two_authors_read_as_three() {
    let m = metadata(&["John Smith", "Anna Johnson", "   "], Some(2023));
    let f = CitationFormatter::new(CitationStyle::Apa);
    assert_eq!(
        f.format_reference(&m, None),
        "Smith, J. & Johnson, A. (2023) T."
    );
    // Python said "(Smith et al., 2023)" here.
    assert_eq!(
        f.format_inline_citation(&m, None),
        "(Smith & Johnson, 2023)"
    );
}

/// The other direction, and the false attribution: Python's
/// `get_first_author_surname()` read `authors[0]` unfiltered, so a blank first
/// author rendered `(Unknown & Johnson, 2023)` and a label `Unknown2023` —
/// even though the reference named Johnson.
#[test]
fn a_blank_first_author_is_not_attributed_to_unknown() {
    let m = metadata(&["   ", "Anna Johnson"], Some(2023));
    let f = CitationFormatter::new(CitationStyle::Apa);
    assert_eq!(f.format_reference(&m, None), "Johnson, A. (2023) T.");
    // Python said "(Unknown & Johnson, 2023)".
    assert_eq!(f.format_inline_citation(&m, None), "(Johnson, 2023)");
    // Python said "Unknown2023", which `create_citation_marker` would then
    // write into a stored marker.
    assert_eq!(m.generate_label(), "Johnson2023");
}

/// A blank trailing author used to be counted as a second author, so a
/// one-author paper rendered as an ampersand pair.
#[test]
fn a_trailing_blank_author_does_not_invent_a_second_author() {
    let m = metadata(&["John Smith", "   "], Some(2023));
    let f = CitationFormatter::new(CitationStyle::Apa);
    assert_eq!(f.format_reference(&m, None), "Smith, J. (2023) T.");
    // Python said "(Smith & Unknown, 2023)".
    assert_eq!(f.format_inline_citation(&m, None), "(Smith, 2023)");
}

/// An all-blank list is an author-less document, and every style already has
/// a branch for that. This is the case that keeps the fix from over-reaching.
#[test]
fn an_all_blank_author_list_reads_as_no_authors() {
    let m = metadata(&["   ", "\t"], Some(2023));
    assert_eq!(m.named_authors().len(), 0);
    assert_eq!(m.first_author_surname(), "Unknown");
    assert_eq!(m.generate_label(), "Unknown2023");
    for style in CitationStyle::all() {
        let f = CitationFormatter::new(style);
        assert!(
            f.format_reference(&m, Some(1)).contains("Unknown author"),
            "{style} should name no author"
        );
    }
}

/// The count is a property of the type, so no consumer can bypass it. This is
/// the structural half of the fix: Python had a private formatter helper that
/// three of four call paths forgot to use.
#[test]
fn every_author_consumer_sees_the_same_count() {
    let m = metadata(&["A One", "", "  ", "B Two"], Some(2020));
    assert_eq!(m.named_authors(), vec!["A One", "B Two"]);
    assert_eq!(m.author_count(), 2);
    for style in CitationStyle::all() {
        let inline = CitationFormatter::new(style).format_inline_citation(&m, None);
        assert!(
            !inline.contains("et al"),
            "{style} has two named authors, so no et al: {inline}"
        );
    }
}

// ---------------------------------------------------------------------------
// Upstream-faithful oddities — kept, not tidied (docs/DECISIONS.md)
// ---------------------------------------------------------------------------

/// The register records this as one of five upstream-faithful oddities, pinned
/// by a Python test naming it. `"Firstname Surname"` is a naive split, so
/// particles are lost — only the inverted format keeps them.
#[test]
fn author_surname_is_a_naive_split_and_stays_one() {
    assert_eq!(author_surname("Jan van der Berg"), "Berg");
    assert_eq!(author_surname("van der Berg, Jan"), "van der Berg");
    assert_eq!(author_surname("Aristotle"), "Aristotle");
    assert_eq!(author_surname("   "), "Unknown");
}

/// `"Smithn.d."` — no separator, no space. Pinned by the register.
#[test]
fn a_label_without_a_year_is_smith_n_d() {
    assert_eq!(
        metadata(&["John Smith"], None).generate_label(),
        "Smithn.d."
    );
}

/// Harvard's natural branch keeps a middle initial's period; APA's inserts a
/// space; Vancouver drops the separator entirely. Three styles, three answers
/// for the same name — and only the differential oracle catches getting one of
/// them wrong, which is how this was found.
#[test]
fn the_three_initial_styles_differ_on_purpose() {
    let m = metadata(&["John A. Smith"], Some(2023));
    let harvard = CitationFormatter::new(CitationStyle::Harvard).format_reference(&m, None);
    let apa = CitationFormatter::new(CitationStyle::Apa).format_reference(&m, None);
    let vancouver = CitationFormatter::new(CitationStyle::Vancouver).format_reference(&m, None);
    assert!(harvard.starts_with("Smith, J.A."), "harvard: {harvard}");
    assert!(apa.starts_with("Smith, J. A."), "apa: {apa}");
    assert!(vancouver.contains("Smith JA"), "vancouver: {vancouver}");
}

/// APA elides the middle of a long list: six names, then `...`, then the
/// **last** name. Pinned by `test_eight_authors_elide_the_middle`.
#[test]
fn apa_elides_the_middle_of_a_long_author_list() {
    // Distinct surnames, so "which name was kept" is answerable. A generated
    // `Author{i} Given` list has one shared surname and cannot distinguish
    // them — which is what an earlier cut of this test got wrong.
    let mut m = DocumentMetadata::new(1, "T");
    m.authors = [
        "Alpha One",
        "Bravo Two",
        "Charlie Three",
        "Delta Four",
        "Echo Five",
        "Foxtrot Six",
        "Golf Seven",
        "Hotel Eight",
    ]
    .iter()
    .map(|s| (*s).to_string())
    .collect();
    let out = CitationFormatter::new(CitationStyle::Apa).format_reference(&m, None);
    assert!(out.contains(", ..., & "), "an ellipsis is expected: {out}");
    // APA inverts to "Surname, I.", so the surnames are the first words.
    let block = out.split(" (").next().expect("author block");
    assert_eq!(
        block.matches(", ..., & ").count(),
        1,
        "one ellipsis: {block}"
    );
    assert!(
        block.ends_with("Eight, H."),
        "the last author is kept: {block}"
    );
    assert!(!block.contains("Seven"), "the seventh is elided: {block}");
}

/// Harvard appends `"and et al."` — which reads oddly and is upstream's.
#[test]
fn harvard_appends_and_et_al() {
    let mut m = DocumentMetadata::new(1, "T");
    m.authors = [
        "Alpha One",
        "Bravo Two",
        "Charlie Three",
        "Delta Four",
        "Echo Five",
        "Foxtrot Six",
        "Golf Seven",
    ]
    .iter()
    .map(|s| (*s).to_string())
    .collect();
    let out = CitationFormatter::new(CitationStyle::Harvard).format_reference(&m, None);
    assert!(out.contains("and et al."), "harvard: {out}");
}

/// Vancouver stops at the sixth name and appends a bare `et al`.
#[test]
fn vancouver_stops_at_the_sixth_name() {
    assert_eq!(MAX_AUTHORS_BEFORE_ET_AL, 6);
    let mut m = DocumentMetadata::new(1, "T");
    m.authors = [
        "Alpha One",
        "Bravo Two",
        "Charlie Three",
        "Delta Four",
        "Echo Five",
        "Foxtrot Six",
        "Golf Seven",
    ]
    .iter()
    .map(|s| (*s).to_string())
    .collect();
    let out = CitationFormatter::new(CitationStyle::Vancouver).format_reference(&m, Some(1));
    // Vancouver renders "Firstname Surname" as "Surname I", so the surnames are
    // the *second* word of each. Counting the author block's entries states the
    // rule without depending on that.
    let block = out
        .trim_start_matches("1. ")
        .split(". ")
        .next()
        .expect("author block");
    let names: Vec<&str> = block.split(", ").collect();
    assert_eq!(names.len(), 7, "six names plus et al: {block}");
    assert_eq!(names[6], "et al", "the sentinel is last: {block}");
    assert!(!block.contains("Seven"), "the seventh is dropped: {block}");
}

/// An empty title renders as `"Untitled"` — and **without** a period, because
/// the Python helper returns early rather than falling through to its
/// append-a-period branch. Pinned by the oracle too.
#[test]
fn an_empty_title_is_untitled_without_a_period() {
    let m = DocumentMetadata::new(1, "");
    let out = CitationFormatter::new(CitationStyle::Vancouver).format_reference(&m, Some(1));
    assert!(out.contains("Untitled"), "{out}");
    assert!(!out.contains("Untitled."), "no period is appended: {out}");
}

/// A marker carrying a `]` cannot parse, because the label runs to the first
/// `]`. The grammar is `[^\]]+`, so this is a documented limit rather than a
/// defect.
#[test]
fn a_label_containing_a_closing_bracket_ends_the_marker_early() {
    let parsed = bmlib::citations::parse_citations("[@id:1:a]b]");
    assert_eq!(parsed.len(), 1);
    assert_eq!(parsed[0].label, "a");
}

/// Positions are **character** offsets, matching Python's `match.start()` on a
/// `str`. A byte-offset implementation would disagree on any non-ASCII prefix.
#[test]
fn positions_are_character_offsets_not_byte_offsets() {
    let text = "Grüße 日本 [@id:1:A]";
    let parsed = bmlib::citations::parse_citations(text);
    assert_eq!(parsed.len(), 1);
    let expected = text.chars().position(|c| c == '[').unwrap();
    assert_eq!(parsed[0].position, expected);
}
