// bmlib — shared library for biomedical literature tools
// Copyright (C) 2024-2026 Dr Horst Herb
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

//! The differential oracle: Rust versus Python, over the context processor and
//! the text utilities it depends on.
//!
//! Same instrument as `citations_oracle`, second corpus. `context_cases.json`
//! plus `context_expected.json` are generated by running the Python library
//! (`rust/oracle/dump_context.py`), so a case here cannot be wrong in the same
//! direction as the port.
//!
//! The processors below mirror the deterministic stand-ins in that script —
//! `EchoProcessor`, `DecoratingProcessor`, `FailingProcessor`,
//! `GrowingProcessor` — so the two sides exercise the same state machines.
//!
//! Regenerating (from the repository root):
//!
//! ```text
//! .venv/bin/python rust/oracle/dump_context.py < rust/oracle/context_cases.json \
//!     > rust/bmlib/tests/data/context_expected.json
//! ```

use std::collections::BTreeMap;
use std::sync::Arc;

use bmlib::context_processor::base::{run_all, ItemRef, ProcessingCore};
use bmlib::context_processor::{
    ConfigError, ConsolidationStrategy, ExtractionResult, Item, IterativeContextProcessor,
    OversizedItemStrategy, ProcessingConfig, ProcessingResult, ProgressCallback, TextItem,
};
use bmlib::llm::text_utils::{combine_title_and_text, get_text_with_priority, TextChunker};
use serde_json::{json, Value};

const CASES: &str = include_str!("data/context_cases.json");
const EXPECTED: &str = include_str!("data/context_expected.json");

// ---------------------------------------------------------------------------
// Deterministic stand-ins, mirroring the Python script
// ---------------------------------------------------------------------------

/// Extraction returns a fixed string.
struct EchoProcessor {
    core: ProcessingCore,
    reply: String,
    decorate: bool,
    fail_on: Vec<usize>,
    echo_batch: bool,
}

impl EchoProcessor {
    fn new(reply: &str, config: ProcessingConfig) -> Self {
        EchoProcessor {
            core: ProcessingCore::new(config, None).expect("valid config"),
            reply: reply.to_string(),
            decorate: false,
            fail_on: Vec::new(),
            echo_batch: false,
        }
    }

    fn decorating(config: ProcessingConfig) -> Self {
        let mut p = Self::new("ok", config);
        p.decorate = true;
        p
    }

    fn failing(config: ProcessingConfig, fail_on: Vec<usize>) -> Self {
        let mut p = Self::new("ok", config);
        p.fail_on = fail_on;
        p
    }

    fn growing(config: ProcessingConfig) -> Self {
        let mut p = Self::new("ok", config);
        p.echo_batch = true;
        p
    }

    fn run(&self, items: &[ItemRef], query: &str, store_intermediate: bool) -> ProcessingResult {
        run_all(
            self,
            &self.core,
            items,
            query,
            &self.core.config,
            store_intermediate,
        )
    }
}

impl IterativeContextProcessor for EchoProcessor {
    fn config(&self) -> &ProcessingConfig {
        &self.core.config
    }

    fn format_item(&self, item: &dyn Item, index: usize) -> String {
        if self.decorate {
            format!("[{index}] {}", item.render(index))
        } else {
            item.render(index)
        }
    }

    fn extract_from_batch(
        &self,
        batch_content: &str,
        _query: &str,
        batch_metadata: &BTreeMap<String, Value>,
    ) -> Result<ExtractionResult, Box<dyn std::error::Error + Send + Sync>> {
        let batch_index = batch_metadata
            .get("batch_index")
            .and_then(Value::as_u64)
            .unwrap_or(0) as usize;
        if self.fail_on.contains(&batch_index) {
            return Err(Box::new(std::io::Error::other("boom")));
        }
        if self.echo_batch {
            return Ok(ExtractionResult::new(batch_content));
        }
        Ok(ExtractionResult::new(&self.reply))
    }

    fn progress_callback(&self) -> Option<&ProgressCallback> {
        None
    }
}

// ---------------------------------------------------------------------------
// Case plumbing
// ---------------------------------------------------------------------------

fn text_items(items: &[Value]) -> Vec<ItemRef> {
    items
        .iter()
        .map(|v| Arc::new(TextItem::new(v.as_str().unwrap_or_default())) as ItemRef)
        .collect()
}

fn config_from(spec: &Value) -> Result<ProcessingConfig, ConfigError> {
    let mut c = ProcessingConfig::default();
    if let Some(v) = spec.get("max_context_chars").and_then(Value::as_u64) {
        c.max_context_chars = v as usize;
    }
    if let Some(v) = spec.get("overlap_chars").and_then(Value::as_u64) {
        c.overlap_chars = v as usize;
    }
    if let Some(v) = spec.get("max_recursion_depth").and_then(Value::as_u64) {
        c.max_recursion_depth = v as usize;
    }
    if let Some(v) = spec.get("min_items_for_recursion").and_then(Value::as_u64) {
        c.min_items_for_recursion = v as usize;
    }
    if let Some(v) = spec.get("min_confidence_threshold").and_then(Value::as_f64) {
        c.min_confidence_threshold = v;
    }
    if let Some(v) = spec.get("continue_on_error").and_then(Value::as_bool) {
        c.continue_on_error = v;
    }
    if let Some(v) = spec.get("preserve_metadata").and_then(Value::as_bool) {
        c.preserve_metadata = v;
    }
    if let Some(v) = spec.get("oversized_item_strategy").and_then(Value::as_str) {
        c.oversized_item_strategy = match v {
            "truncate" => OversizedItemStrategy::Truncate,
            "skip" => OversizedItemStrategy::Skip,
            "fail" => OversizedItemStrategy::Fail,
            _ => OversizedItemStrategy::Split,
        };
    }
    if let Some(v) = spec.get("consolidation_strategy").and_then(Value::as_str) {
        c.consolidation_strategy = match v {
            "weighted" => ConsolidationStrategy::Weighted,
            "deduplicate" => ConsolidationStrategy::Deduplicate,
            _ => ConsolidationStrategy::Concatenate,
        };
    }
    c.validate()?;
    Ok(c)
}

fn chunker(args: &Value) -> Result<TextChunker, String> {
    TextChunker::new(
        args["chunk_size"].as_u64().unwrap_or(100) as usize,
        args.get("overlap").and_then(Value::as_u64).unwrap_or(0) as usize,
        args.get("boundary_aware")
            .and_then(Value::as_bool)
            .unwrap_or(true),
        args.get("min_chunk_size")
            .and_then(Value::as_u64)
            .unwrap_or(500) as usize,
    )
    .map_err(|e| e.to_string())
}

fn result_json(r: &ExtractionResult) -> Value {
    json!({
        "content": r.content,
        "confidence": r.confidence,
        "is_error": r.is_error,
        "error_message": r.error_message,
        "recursion_level": r.recursion_level,
        "source_indices": r.source_indices,
        "content_length": r.content_length(),
        "is_valid": r.is_valid(),
    })
}

fn processing_result_json(pr: &ProcessingResult) -> Value {
    let stats_batches = pr
        .processing_stats
        .get("batches_per_level")
        .cloned()
        .unwrap_or(Value::Null);
    let stats_items = pr
        .processing_stats
        .get("items_per_level")
        .cloned()
        .unwrap_or(Value::Null);
    json!({
        "content": pr.content(),
        "status": pr.status.as_str(),
        "total_items_processed": pr.total_items_processed,
        "batches_created": pr.batches_created,
        "recursion_levels_used": pr.recursion_levels_used,
        "failed_batches": pr.failed_batches,
        "skipped_items": pr.skipped_items,
        "successful_batches": pr.successful_batches,
        "success_rate": pr.success_rate(),
        "is_complete": pr.is_complete(),
        "is_partial": pr.is_partial(),
        "has_failures": pr.has_failures(),
        "error_message": pr.error_message,
        "final_result": result_json(&pr.final_result),
        "batches_per_level": stats_batches,
        "items_per_level": stats_items,
    })
}

fn run(case: &Value) -> Value {
    let name = case["name"].as_str().unwrap_or_default();
    let fn_name = case["fn"].as_str().unwrap_or_default();
    let args = &case["args"];

    match fn_name {
        "chunk_text" => {
            let c = chunker(args).expect("chunker");
            let text = args["text"].as_str().unwrap_or_default();
            json!(c
                .chunk_text(text)
                .iter()
                .map(|ch| json!({
                    "content": ch.content,
                    "start_pos": ch.start_pos,
                    "end_pos": ch.end_pos,
                    "chunk_index": ch.chunk_index,
                    "total_chunks": ch.total_chunks,
                    "size": ch.size(),
                }))
                .collect::<Vec<_>>())
        }
        "chunk_info" => {
            let c = chunker(args).expect("chunker");
            let info = c.chunk_info(args["text"].as_str().unwrap_or_default());
            json!({
                "text_length": info.text_length,
                "num_chunks": info.num_chunks,
                "chunk_size": info.chunk_size,
                "overlap": info.overlap,
                "avg_chunk_size": info.avg_chunk_size,
                "last_chunk_size": info.last_chunk_size,
            })
        }
        "chunker_error" => match chunker(args) {
            Ok(_) => json!({"raised": false}),
            Err(message) => json!({"raised": true, "type": "ValueError", "message": message}),
        },
        "get_text_with_priority" => {
            let mut doc: BTreeMap<String, String> = BTreeMap::new();
            if let Some(obj) = args["document"].as_object() {
                for (k, v) in obj {
                    doc.insert(k.clone(), v.as_str().unwrap_or_default().to_string());
                }
            }
            let (text, source) = get_text_with_priority(
                &doc,
                args.get("prefer_full_text")
                    .and_then(Value::as_bool)
                    .unwrap_or(true),
            );
            json!({"text": text, "source": source})
        }
        "combine_title_and_text" => json!(combine_title_and_text(
            args["title"].as_str().unwrap_or_default(),
            args["text"].as_str().unwrap_or_default(),
            args.get("max_title_length")
                .and_then(Value::as_u64)
                .unwrap_or(500) as usize
        )),
        "config_validate" => match config_from(&args["config"]) {
            Ok(_) => json!({"raised": false}),
            Err(e) => json!({"raised": true, "message": e.to_string(), "type": "ValueError"}),
        },
        "process" => {
            let config = config_from(&args["config"]).expect("valid config for process cases");
            let items = text_items(
                args["items"]
                    .as_array()
                    .cloned()
                    .unwrap_or_default()
                    .as_slice(),
            );
            let kind = args
                .get("processor")
                .and_then(Value::as_str)
                .unwrap_or("echo");
            let store = args
                .get("store_intermediate")
                .and_then(Value::as_bool)
                .unwrap_or(false);
            let pr = match kind {
                "decorating" => EchoProcessor::decorating(config).run(&items, "q", store),
                "failing" => {
                    let fail_on: Vec<usize> = args
                        .get("fail_on")
                        .and_then(Value::as_array)
                        .map(|a| {
                            a.iter()
                                .filter_map(Value::as_u64)
                                .map(|n| n as usize)
                                .collect()
                        })
                        .unwrap_or_default();
                    EchoProcessor::failing(config, fail_on).run(&items, "q", store)
                }
                "growing" => EchoProcessor::growing(config).run(&items, "q", store),
                _ => EchoProcessor::new("ok", config).run(&items, "q", store),
            };

            let mut out = processing_result_json(&pr);
            if store {
                let counts: Vec<usize> = pr
                    .intermediate_results
                    .as_ref()
                    .map(|levels| levels.iter().map(Vec::len).collect())
                    .unwrap_or_default();
                out["intermediate_result_counts"] = json!(counts);
            }
            out
        }
        other => panic!("case {name:?}: unknown fn {other:?}"),
    }
}

#[test]
fn the_port_agrees_with_python_on_every_case() {
    let cases: Value = serde_json::from_str(CASES).expect("cases parse");
    let expected: Value = serde_json::from_str(EXPECTED).expect("expected parse");
    let cases = cases.as_array().expect("cases is a list");
    let expected = expected.as_array().expect("expected is a list");
    assert_eq!(cases.len(), expected.len(), "regenerate the expectations");

    let mut failures: Vec<String> = Vec::new();
    for (case, want) in cases.iter().zip(expected.iter()) {
        let name = case["name"].as_str().unwrap_or_default();
        assert_eq!(name, want["name"].as_str().unwrap_or_default());
        assert!(
            want["ok"].as_bool().unwrap_or(false),
            "case {name:?} errored in Python: {} — a case that does not run there \
             cannot be a differential expectation",
            want["error"]
        );
        let got = run(case);
        if got != want["value"] {
            failures.push(format!(
                "  {name}\n    python: {}\n    rust:   {}",
                serde_json::to_string(&want["value"]).unwrap_or_default(),
                serde_json::to_string(&got).unwrap_or_default()
            ));
        }
    }

    assert!(
        failures.is_empty(),
        "{} of {} cases diverge from Python:\n{}",
        failures.len(),
        cases.len(),
        failures.join("\n")
    );
}
